// Code generated by "stringer -type Status"; DO NOT EDIT.

package email

import "strconv"

const _Status_name = "QueuedSentSuccessfullyFailedAttemptToSendDead"

var _Status_index = [...]uint8{0, 6, 22, 41, 45}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
