// Code generated by "stringer -type=SendStatus"; DO NOT EDIT.

package status

import "strconv"

const _SendStatus_name = "SentFailedQueued"

var _SendStatus_index = [...]uint8{0, 4, 10, 16}

func (i SendStatus) String() string {
	if i < 0 || i >= SendStatus(len(_SendStatus_index)-1) {
		return "SendStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SendStatus_name[_SendStatus_index[i]:_SendStatus_index[i+1]]
}
