// Code generated by protoc-gen-go. DO NOT EDIT.
// source: publishedEmail.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishedEmail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []string `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []string `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject              string   `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	PublishedAt          int64    `protobuf:"varint,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	StatusId             int64    `protobuf:"varint,9,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishedEmail) Reset()         { *m = PublishedEmail{} }
func (m *PublishedEmail) String() string { return proto.CompactTextString(m) }
func (*PublishedEmail) ProtoMessage()    {}
func (*PublishedEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_aafcfb180c438fef, []int{0}
}

func (m *PublishedEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishedEmail.Unmarshal(m, b)
}
func (m *PublishedEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishedEmail.Marshal(b, m, deterministic)
}
func (m *PublishedEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishedEmail.Merge(m, src)
}
func (m *PublishedEmail) XXX_Size() int {
	return xxx_messageInfo_PublishedEmail.Size(m)
}
func (m *PublishedEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishedEmail.DiscardUnknown(m)
}

var xxx_messageInfo_PublishedEmail proto.InternalMessageInfo

func (m *PublishedEmail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PublishedEmail) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *PublishedEmail) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *PublishedEmail) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *PublishedEmail) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *PublishedEmail) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *PublishedEmail) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *PublishedEmail) GetPublishedAt() int64 {
	if m != nil {
		return m.PublishedAt
	}
	return 0
}

func (m *PublishedEmail) GetStatusId() int64 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

func init() {
	proto.RegisterType((*PublishedEmail)(nil), "dto.PublishedEmail")
}

func init() { proto.RegisterFile("publishedEmail.proto", fileDescriptor_aafcfb180c438fef) }

var fileDescriptor_aafcfb180c438fef = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0x4a, 0xc7, 0x30,
	0x10, 0xc7, 0x49, 0x52, 0xdb, 0xe6, 0x94, 0x22, 0x87, 0xc3, 0x81, 0x4b, 0x75, 0xea, 0xe4, 0xe2,
	0x13, 0x38, 0x38, 0xb8, 0x49, 0x5f, 0xa0, 0x34, 0x49, 0xc5, 0x48, 0x4b, 0x4a, 0x73, 0x1d, 0x7c,
	0x4f, 0x1f, 0x48, 0x92, 0xf2, 0x2b, 0xfc, 0xb6, 0xef, 0x9f, 0xe3, 0xc3, 0xf7, 0xe0, 0x61, 0xdd,
	0xcd, 0xec, 0xe3, 0xf7, 0xe4, 0xde, 0x97, 0xd1, 0xcf, 0x2f, 0xeb, 0x16, 0x38, 0xa0, 0x72, 0x1c,
	0x9e, 0xff, 0x04, 0x34, 0x9f, 0x57, 0x2d, 0x36, 0x20, 0xbd, 0x23, 0xd1, 0x8a, 0x4e, 0xf5, 0xd2,
	0x3b, 0x44, 0x28, 0xbe, 0xb6, 0xb0, 0x90, 0x6c, 0x45, 0xa7, 0xfb, 0xac, 0xd3, 0x0d, 0x07, 0x52,
	0xad, 0xea, 0x74, 0x2f, 0x39, 0x24, 0x6f, 0x2d, 0x15, 0x87, 0xb7, 0x16, 0xef, 0x41, 0x19, 0x6b,
	0xe9, 0x26, 0x07, 0x49, 0x22, 0x41, 0x15, 0x77, 0xf3, 0x33, 0x59, 0xa6, 0x32, 0x83, 0x2e, 0x36,
	0xf1, 0x4d, 0x70, 0xbf, 0x54, 0x1d, 0xfc, 0xa4, 0xf1, 0x09, 0xee, 0xce, 0xcd, 0xc3, 0xc8, 0x54,
	0xe7, 0x35, 0xb7, 0x67, 0xf6, 0xc6, 0xf8, 0x08, 0x3a, 0xf2, 0xc8, 0x7b, 0x1c, 0xbc, 0x23, 0x9d,
	0xfb, 0xfa, 0x08, 0x3e, 0x9c, 0x29, 0xf3, 0x8b, 0xaf, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0xa7, 0xa5, 0x77, 0xfa, 0x00, 0x00, 0x00,
}
