// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queuedEmail.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusEvent struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	At                   uint64   `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusEvent) Reset()         { *m = StatusEvent{} }
func (m *StatusEvent) String() string { return proto.CompactTextString(m) }
func (*StatusEvent) ProtoMessage()    {}
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_21d0a80e5c012a88, []int{0}
}

func (m *StatusEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusEvent.Unmarshal(m, b)
}
func (m *StatusEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusEvent.Marshal(b, m, deterministic)
}
func (m *StatusEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusEvent.Merge(m, src)
}
func (m *StatusEvent) XXX_Size() int {
	return xxx_messageInfo_StatusEvent.Size(m)
}
func (m *StatusEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StatusEvent proto.InternalMessageInfo

func (m *StatusEvent) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StatusEvent) GetAt() uint64 {
	if m != nil {
		return m.At
	}
	return 0
}

type QueuedEmail struct {
	Id                   uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string         `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string       `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []string       `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []string       `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject              string         `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string         `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Status               []*StatusEvent `protobuf:"bytes,8,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueuedEmail) Reset()         { *m = QueuedEmail{} }
func (m *QueuedEmail) String() string { return proto.CompactTextString(m) }
func (*QueuedEmail) ProtoMessage()    {}
func (*QueuedEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_21d0a80e5c012a88, []int{1}
}

func (m *QueuedEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuedEmail.Unmarshal(m, b)
}
func (m *QueuedEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuedEmail.Marshal(b, m, deterministic)
}
func (m *QueuedEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedEmail.Merge(m, src)
}
func (m *QueuedEmail) XXX_Size() int {
	return xxx_messageInfo_QueuedEmail.Size(m)
}
func (m *QueuedEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedEmail.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedEmail proto.InternalMessageInfo

func (m *QueuedEmail) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueuedEmail) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *QueuedEmail) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *QueuedEmail) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *QueuedEmail) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *QueuedEmail) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *QueuedEmail) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *QueuedEmail) GetStatus() []*StatusEvent {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusEvent)(nil), "dto.StatusEvent")
	proto.RegisterType((*QueuedEmail)(nil), "dto.QueuedEmail")
}

func init() { proto.RegisterFile("queuedEmail.proto", fileDescriptor_21d0a80e5c012a88) }

var fileDescriptor_21d0a80e5c012a88 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x3b, 0xa4, 0x74, 0x22, 0x50, 0x99, 0x05, 0x9a, 0xa5, 0xd5, 0x95, 0x57, 0x59,
	0x80, 0x38, 0x42, 0x0f, 0x80, 0x39, 0x81, 0xff, 0x90, 0x82, 0x28, 0x03, 0xcd, 0x18, 0x89, 0xb3,
	0x71, 0x39, 0x64, 0x97, 0x42, 0x77, 0xef, 0xb3, 0x3d, 0x9f, 0xfc, 0x06, 0x6e, 0x3e, 0x4a, 0x2e,
	0x39, 0xed, 0xf6, 0x7e, 0x7e, 0x9d, 0xde, 0x0f, 0x2c, 0x8c, 0x3a, 0x09, 0x6f, 0x1f, 0x60, 0x7c,
	0x12, 0x2f, 0x65, 0xd9, 0x7d, 0xe6, 0x37, 0xc1, 0x5b, 0x18, 0x96, 0x86, 0xd4, 0x99, 0xce, 0x5e,
	0xb9, 0x5f, 0xc2, 0x6b, 0x50, 0x5e, 0x48, 0x99, 0xce, 0xf6, 0x4e, 0x79, 0xd9, 0x7e, 0x77, 0x30,
	0x3e, 0xfe, 0x1b, 0xeb, 0xfd, 0x9c, 0xda, 0x4c, 0xef, 0xd4, 0x9c, 0x10, 0xa1, 0x7f, 0x3e, 0xf0,
	0xbe, 0x4d, 0xac, 0x5d, 0xcb, 0xf5, 0x8d, 0x30, 0x69, 0xa3, 0xed, 0xda, 0x29, 0xe1, 0xca, 0x31,
	0x52, 0x7f, 0xe4, 0x18, 0x71, 0x03, 0x3a, 0xc4, 0x48, 0x17, 0xed, 0xa0, 0x46, 0x24, 0x58, 0x2d,
	0x25, 0xbc, 0xe4, 0x28, 0x34, 0x34, 0xd1, 0x09, 0xab, 0x3f, 0x70, 0xfa, 0xa2, 0xd5, 0xd1, 0x5f,
	0x33, 0xda, 0xbf, 0xbf, 0x5f, 0x1a, 0x6d, 0xc7, 0xbb, 0xcd, 0x94, 0x84, 0xa7, 0xb3, 0x76, 0xa7,
	0x36, 0x61, 0x68, 0x0b, 0xb8, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x96, 0xbf, 0x4e, 0xef, 0x15,
	0x01, 0x00, 0x00,
}
